source: .
destination: ./docs
title: KnowledgeBase Archive
description: An Archive of Early Microsoft KnowledgeBase Articles
theme: jekyll-theme-tactile
exclude: ["node_modules","tmp","txt","Gemfile*","package*.json","scripts"]
