source: .
destination: ./docs
baseurl: /kbarchive
url: http://jeffpar.github.io
repository: kbarchive/jeffpar.github.io
title: "KnowledgeBase Archive"
description: "An Archive of Early Microsoft KnowledgeBase Articles"
theme: jekyll-theme-tactile
exclude: ["kb","node_modules","tmp","txt","Gemfile*","package*.json","scripts"]
